### ISSUE TITLE
Will poethepoet delete the virtual environment in poetry?

### ISSUE THREAD

**Issue by lfygh** [nat-n/poethepoet#171] opened 2023-10-08 04:54 UTC
I installed Poe the Poet into my poetry project.
```
[tool.poetry.group.dev.dependencies]
poethepoet = "^0.22.1"
```
before run poe command, env information is as follows:
```
 > poetry env list
chat-action-server-Jyf8p_KH-py3.9 (Activated)

```
and run poe commnd 
```
>poetry run poe dev 
```
then print the  env information,there is nothing output.
```
poetry env list
```

**Comment by nat-n** [comment] 2023-10-08 11:57
Hi @lfygh, this is surprising, since poe does not have any capabilities for directly managing the virtualenv. Are you sure that's what happened?

If you can give more information about the context and how to reproduce this issue I'll try work out what's going on.

**Comment by nat-n** [comment] 2023-10-25 18:43
I'm going to close this issue now because it's unclear if there's really an issue to be addressed here.

**Closed by nat-n** 2023-10-25 18:43 UTC
